services:
  postgres:
    image: postgres:latest
    container_name: postgres_casbin_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./psqldata:/var/lib/postgresql/data
    restart: unless-stopped